image: registry.gitlab.com/arenaoftitans/arena-of-titans-api/dev/aot-api:latest

stages:
  - checks
  - build artifacts
  - build docker image

lint:
  stage: checks
  script:
    - make lint

tests:
  stage: checks
  script:
    - make CI_TESTS_TIMEOUT=5 ci

build:
  stage: build docker image
  image: docker:latest
  services:
    - docker:dind
  variables:
    VERSION: $CI_COMMIT_REF_SLUG
  script:
    - if [[ "${VERSION}" == master ]]; then VERSION="${VERSION}-$(date +%y-%m-%d-%H-%M)"; fi
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - apk update
    - apk add make
    # Dockerignore is there to build base and dev images.
    # If we keep it, we won't pass the code to the docker daemon.
    - rm -rf .dockerignore
    - make VERSION=$VERSION dockerimage
    - docker push registry.gitlab.com/arenaoftitans/arena-of-titans-api:$VERSION
  when: manual
