image: registry.gitlab.com/arenaoftitans/arena-of-titans-api/dev/aot-api:latest

stages:
  - checks

lint:
  stage: checks
  script:
    - make lint

tests:
  stage: checks
  services:
      - redis:latest
  script:
    - make CI_TESTS_TIMEOUT=5 CACHE_HOST=redis tests
