image: registry.gitlab.com/arenaoftitans/arena-of-titans-api/dev/aot-api:latest

stages:
  - checks

lint:
  stage: checks
  script:
    - make lint

tests:
  stage: checks
  script:
    - make CI_TESTS_TIMEOUT=5 ci
