################################################################################
# Copyright (C) 2017 by Arena of Titans Contributors.
#
# This file is part of Arena of Titans.
#
# Arena of Titans is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Arena of Titans is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Arena of Titans. If not, see <http://www.gnu.org/licenses/>.
################################################################################

version: '3'

services:
  aot-dev-api:
    image: registry.gitlab.com/arenaoftitans/arena-of-titans-api/dev/aot-api:18.12.1
    command: ["python3", "-m", "aot", "--reload"]
    depends_on:
      - aot-redis
    environment:
      ENV: development
      PYTHONBREAKPOINT: pudb.set_trace
    ports:
      - "8181:8181"
      - "6900:6900"
    tty: true
    stdin_open: true
    volumes:
      - ./:/opt/aot-api:Z
    working_dir: /opt/aot-api
  aot-gateway:
    image: registry.gitlab.com/arenaoftitans/game-gateway:v1.0.0
    depends_on:
      - aot-dev-api
    environment:
      API_HOST: aot-dev-api
    ports:
      - "8180:8180"
  aot-redis:
    image: docker.io/redis
    tty: true
