[api]
allow_debug = false
# Keep in sync with config in aot-infra
socket = '/aot-api/external/aot-api-ws-prod-{version}.sock'
# The group for the unix socket
socket_group = 'nginx'


[cache]
socket = '/aot-api/external/redis.sock'


[uwsgi]
# Don't append .sock, it is appended with the version in the template.
socket = '/var/run/uwsgi/aot-api-prod'
user = 'uwsgi'
