[api]
allow_debug = false
# Keep in sync with config in aot-infra
socket = '/aot-api/external/aot-api-ws-prod-{version}.sock'
# The group for the unix socket
socket_group = 'nginx'


[cache]
host = '127.0.0.1'
port = 6379
socket = '/var/run/redis/aot-api-prod-{version}.sock'
