[api]
allow_debug = false
host = '127.0.0.1'
root = '/home/aot/prod/api/latest'
server_name = 'api.arenaoftitans.com'
# If socket is present and contains a truethy value, the app will be created with unix socket.
socket = '/var/run/uwsgi/aot-api-ws-prod-$1.sock'
# The group for the unix socket
socket_group = 'nginx'
ws_port = 9000


[cache]
server_host = '127.0.0.1'
server_port = 6379


[front]
root = '/home/aot/prod/front/latest'
server_name = 'www.arenaoftitans.com'


[uwsgi]
socket = '/var/run/uwsgi/aot-api-prod.sock'
user = 'uwsgi'
