[api]
allow_debug = false
log_file = 'logs/aot-api.log'
rollbar_enabled = true
rollbar_config = '/opt/aot-api/.rollbar.json'
# Keep in sync with config in aot-infra
socket = '/opt/aot-api/sockets/aot-api-ws-prod-{version}.sock'
# The group for the unix socket
socket_group = 'nginx'


[cache]
socket = '/opt/aot-api/sockets/redis.sock'


[uwsgi]
# Don't append .sock, it is appended with the version in the template.
socket = '/var/run/uwsgi/aot-api-prod'
user = 'uwsgi'
